name: PHP Composer

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: "build and test"
    runs-on: self-hosted

    steps:
    - name: "Checkout code"
      uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.x'
        coverage: none
        tools: composer

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run PHP syntax check
      run: find . -name '*.php' -not -path './vendor/*' -exec php -l {} \;

    - name: "Crear archivo .env"
      run: touch .env

    - run: echo "${{ secrets.PHP_ENV_FILE }}" > .env

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
